# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: GirlsOnCode
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "girlsoncode.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: girlsoncode
github_username:  girlsoncode
disqus_shortname: 
reading_time:     true
words_per_minute: 200



# Default extension for new posts and pages
post_ext: markdown
page_ext: html

# Format titles with titlecase?
titlecase: true

# Where is
data_dir:     _data
plugins_dir:  _plugins
draft_dir:    _drafts


# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft


# Outputting
paginate:       5
permalink:      /:categories/:year/:month/:day/:title/
paginate_path:  /page:num

# Build settings
timezone: America/Sao_Paulo
encoding: utf-8
future: false  # publish future dated posts --  true, false (default) 
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
sass:
  sass_dir: _sass
style: compressed

# Amount of post to show on home page
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: 
  - .htaccess
exclude: 
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README

